### ISSUE TITLE
Taiga keeps freezing.

### ISSUE THREAD

**Issue by hjqwgecftrtw3j** [erengy/taiga#301]
Taiga keeps freezing on EVERYTHING from detecting a new anime that is playing, to clicking on something within the program. I tried re-installing and the program still froze right off the bat when it asks to link up myanimelist!

I have a sad now, because I have lost track of my anime episodes from when I didn't realize it was freezing in the background.

**Comment by erengy** [comment]
Might be the same issue as #270, #271 and #280. In that case, downloading [this build](http://taiga.moe/latest.html) should fix it for you.

**Comment by zakius** [comment]
win10 home x86, latest kodi, latest taiga, z3735 with 1gb ram, taiga freezes the exact moment kodi window becomes active and keeps at it until kodi gets closed
tried the latest build without installer, still the same

**Comment by erengy** [comment]
In your case, it might be related to a Kodi add-on. Please see [this comment](https://github.com/erengy/taiga/issues/34#issuecomment-63471990) for more information.

And happy new year!

**Comment by zakius** [comment]
Unfortunately all I have is clean install and two video add-ons I can't give up on + repo they're installed from, even disabled some built in add-ons I don't intent to use

or... I went through settings again and disabled syncing refresh rate stuff and http and local control and it seem to work, re-enabling http control causes problem to happen again
I hope we can somehow get around it (I don't exactly need it, but it is nice thing to have)

Happy New Year to you too and thanks for your support

**Comment by lpchaim** [comment]
This has been happening to me too, started noticing ever since I updated to Kodi's Krypton release (v17 rc2 here) some days ago. I do use the Emby addon, but disabling it doesn't change this behavior at all, plus it used to work fine with Kodi and Taiga in my previous Jarvis (v16) setup. Oh, I'm currently using the build that was linked in here as well.
I also noticed this showed up in the logs some times:
```
2017-01-08 20:59:14 [Error] http.cpp:93 taiga::HttpClient::OnError | >>
HTTP error #6: Couldn't resolve host name (myanimelist.cdn-dena.com)
Connection mode: 10
```
No idea if that relates at all, but pasting that in my browser results in a redirect to https://akamai-origin.myanimelist.net/ and a 404 error.

**Comment by erengy** [comment]
I just tried out Kodi v17.0 RC2. I didn't have any issues at first, but enabling *Settings* → *Services* → *Control* → *Allow remote control via HTTP* caused Taiga to freeze, as @zakius suggested.

When this option is enabled, Kodi creates some `\Device\Afd\Endpoint` handles with an access code of `0x0016019f`, which causes `NtQueryObject` to hang. In that regard, this issue is similar to #270.

Could you try out [this new build](http://taiga.moe/latest.html) and see if it fixes the issue for you?

**Comment by lpchaim** [comment]
Thank you @erengy, the new build works perfectly on my end! Never imagined the remote control interface would be the problem since I've always had it enabled before, I guess Krypton did change lots of stuff all around.

**Comment by zakius** [comment]
haven't checked if i works for me, but I have a question: it seems that the fix is so experimental it isn't available on the GitHub?
@erengy

**Comment by erengy** [comment]
The fix consists of `0x0016019f` being added to [this list](https://github.com/erengy/taiga/blob/ed6346120c45cce2f308f16d06a04c63eba091a6/src/base/process.cpp#L216-L220). Before committing it to the public repository, I wanted to make sure that it works for you and it doesn't cause valid file handles being skipped.

**Comment by zakius** [comment]
okay, I'll test it for a few days probably and report back    
it's understandable that you wanted to perform kind of closed testing before committing it here

**Comment by zakius** [comment]
no issues for now on my side

**Comment by lpchaim** [comment]
Same here, haven't noticed any anomalies ever since I updated to the provided build.
