### ISSUE TITLE
Discord Rich Presence not working

### ISSUE THREAD

**Issue by Cephel** [erengy/taiga#554]
Is it maybe limited to special media players?

**Comment by erengy** [comment]
You need to have these two options enabled:

- *Tools → Enable auto sharing*
- *Settings → Sharing → Discord → Update rich presence*

Also note that:

- This feature requires using the Discord desktop client (i.e. it doesn't work if you open Discord in a regular web browser).
- Delay time (at *Settings → Recognition*) affects automatic sharing too (I intend to change this behaviour or to make it more obvious in future releases).
- Rich presence updates may take an additional 15 seconds to appear, due to Discord's rate limit.
- It's currently not possible to display "Watching (...)" instead of "Taiga", or the anime image instead of Taiga's own icon.

**Comment by AceTF** [comment]
Same problem here. I have both options enabeld - it is still not working. Using MPC-Player

**Comment by marioandluigi878** [comment]
worked for me all I had to do was change the delay time to about 15 secs and it worked

**Comment by Cephel** [comment]
Both settings are enabled and I left the media player open for 4 hours now

**just to be sure**

It's not working.

**Comment by yahoo1999** [comment]
Shouldn't be Taiga also added to Games list in discord?

Also @erengy I think you should add these information to FAQ page, as it, I guess, will be frequently asked question :smile:

**Comment by Cephel** [comment]
![image](https://user-images.githubusercontent.com/6716857/38396040-3903f042-3936-11e8-8a74-ac5a4311f13a.png)
![image](https://user-images.githubusercontent.com/6716857/38396055-48b10d0e-3936-11e8-8284-892300bfbf24.png)
![image](https://user-images.githubusercontent.com/6716857/38396064-50126304-3936-11e8-9515-ccf3d0a7e860.png)

I **am** using the Discord Desktop client

**Comment by marioandluigi878** [comment]
@Cephel change the delay to 15 secs

**Comment by erengy** [comment]
@Cephel There should be a *Display currently running game as a status message* option at Discord desktop client's *App Settings → Games*. Could you check if it's enabled?

**Comment by lucario386** [comment]
Is it possible to make it so that this doesn't show? (When nothing is playing)
![image](https://user-images.githubusercontent.com/12094600/38406631-8ebbaf58-39a8-11e8-94dd-979263c50567.png)
Not sure if it's possible since you add it as a game in discord. Maybe only allow it to detect if there is a media player open?

**Comment by yahoo1999** [comment]
@lucario386 As I stated earlier, you don't have to add taiga as game in Discord settings. It works without if. 
![unknown](https://user-images.githubusercontent.com/18481896/38409240-f4e4ca8a-3980-11e8-8efb-68ab3fd294b8.png)

**Comment by lucario386** [comment]
@yahoo1999 Oh okay. It works without adding as game but you have to change the delay to 15s. (Which erengy mentioned about it too but I didn't understand till now)

**Comment by erengy** [comment]
To clarify:

- The media player you use doesn't make any difference. If Taiga is able to identify the anime you're watching, then Discord integration should work.
- You don't need to change the delay time to any specific value. Just be aware that Taiga will update your rich presence after the delay, whatever it may be.
- You don't need to add Taiga as a game to Discord desktop client. However, the *Display currently running game as a status message* option must be enabled.

> Is it possible to make it so that this doesn't show? (When nothing is playing)

As far as I'm aware, this is unavoidable. Rich Presence is designed for games (see #450), so using it for other purposes is basically a hack. Discord thinks a game called "Taiga" is still running, even when you're not watching anything.

**Comment by zertap** [comment]
Doesn't work for me either. Not on Win10 nor on Win7. 
Taiga is able to identify the anime. It also does send a HTTP request specified in sharing options properly.

**Comment by phantom-playR** [comment]
Not a big issue, but it doesn't work with the Discord Canary version

**Comment by asakurato** [comment]
Where do you see statuses like this? When I check in Settings-->Games, it shows that Taiga is just running, but nothing else. I think I have enabled all options.
![38409240-f4e4ca8a-3980-11e8-8efb-68ab3fd294b8](https://user-images.githubusercontent.com/20476454/38455826-700e1834-3a8e-11e8-9c51-a591c44beb54.png)

**Comment by yahoo1999** [comment]
@asakurato You don't add Taiga as a game. As @erengy said it will automatically post to rich pressence when all the timers are done. You have to wait the amount of time set in recogintion delay and about 15 seconds of Discord antyspam.

**Comment by asakurato** [comment]
@yahoo1999 I have enabled everything, added Taiga as a game (but it shouldn't be necessary). It discord detects Taiga without adding as a game and I just asked where do I see status like that, not how should it work

**Comment by wopian** [comment]
Do not add Taiga as a game - it will show it as running while you have Taiga running in the background.

You can see the content in the image by clicking your name in the members list on the right.

**Comment by erengy** [comment]
@Cephel As I mentioned previously:

> It's currently not possible to display "Watching (...)" instead of "Taiga", or the anime image instead of Taiga's own icon.

See https://github.com/erengy/taiga/issues/450#issuecomment-378204378 and the following comment for more information.

**Comment by Cephel** [comment]
![image](https://user-images.githubusercontent.com/6716857/38478348-7b4bb460-3bb8-11e8-95ef-cf33a9234f11.png)

I got it to work too, so this can be closed for me atleast. The problem was having to enable display running game in Discord.

**Comment by FichteFoll** [comment]
>Discord thinks a game called "Taiga" is still running, even when you're not watching anything.

I suspect that this detection is based on the pid you include in your metadata  when sending activity, though I haven't looked much further. If this is true, it should be possible to spawn a process just to have its pid be passed to the discord client and then kill the process once the anime is finished.
(If this worked out, please do tell.)

**Comment by Jasonfran** [comment]
@FichteFoll Discord displaying Taiga when idle only happens when you add Taiga as a game inside of Discord. Taiga will display rich presence data without doing that. So by default when Taiga is idling it shows nothing, so there's nothing to fix here.

**Comment by FichteFoll** [comment]
Okay, never mind. I implemented the RPC protocol in Python a while ago and wasn't aware that apprently there is a way to clear the presence - at least in the reference discord-rpc library ([here](https://github.com/discordapp/discord-rpc/blob/2ce9fe068bfb51a223465f57c29d15bf5f4f6336/src/discord_rpc.cpp#L344) and [here](https://github.com/discordapp/discord-rpc/blob/2ce9fe068bfb51a223465f57c29d15bf5f4f6336/src/serialization.cpp#L105)). Turned out to be easier than expected, but their [hard mode docs](https://github.com/discordapp/discord-rpc/blob/master/documentation/hard-mode.md) could've just included that.

**Comment by LotteBestGirl** [comment]
Before it was working fine, but then i resetted the settings and then ramade all the steps and it still doens't work for me, what i am supposed to do?

**Comment by nashartwell** [comment]
The sharing option in settings for me is not working for the rich presence
but when I have the episode already playing and then click on share->discord   from the "Now Playing" tab it works.
I have given it a few minutes from ep start to show up.
I have restarted taiga, discord, and even my computer and still not working. I confirmed after the computer restart that the Rich presence option in the settings is still checked as True

**Comment by erengy** [comment]
If you're still having problems with Discord integration, please read the relevant section under Common Issues at the [Support](http://taiga.moe/#support) page.

@nashartwell That should be related to this:

> Note that the delay time at *Settings → Recognition* affects automatic sharing too.

**Comment by Deterio** [comment]
I think Discord allows dynamic images with Rich Presence as text editors change their icon according to the file extension.

**Comment by votex09** [comment]
To anyone else having issues getting this work, close taiga and run as administrator.  This is the only way I could get it to work.
